"""
preconfigured_apps.py — Registry freigeschalteter Apps für casaos-lxc-bridge

install_type:
  "fixed"   → feste LXC-ID + IP (wie Nextcloud LXC 109)
  "dynamic" → LXC-ID + IP dynamisch aus Bridge-Pool (301–399)
"""
from __future__ import annotations

PRECONFIGURED_APPS: list[dict] = [
    # ── Dynamische Apps (LXC-ID + IP aus User-Subnetz) ───────────────────
    {
        "app_id": "Nextcloud",
        "name": "Nextcloud",
        "tagline": "Ihre Cloud, Ihre Regeln",
        "description": "Datei-Synchronisation, Kalender, Kontakte, Kollaboration und mehr. Vollständige Datenkontrolle auf Ihrem eigenen Server.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/nextcloud.png",
        "category": "Cloud",
        "port": 10081,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "Syncthing",
        "name": "Syncthing",
        "tagline": "Peer-to-Peer Datei-Synchronisation ohne Cloud",
        "description": "Synchronisiert Dateien direkt zwischen Geräten — verschlüsselt, dezentral, ohne Cloud-Dienst.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/syncthing.png",
        "category": "Backup",
        "port": 8384,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "Vaultwarden",
        "name": "Vaultwarden",
        "tagline": "Bitwarden-kompatibler Passwort-Manager",
        "description": "Leichtgewichtige Bitwarden-Server-Implementierung. Alle Bitwarden-Apps funktionieren damit.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/vaultwarden.png",
        "category": "Security",
        "port": 10380,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "Gitea",
        "name": "Gitea",
        "tagline": "Self-hosted Git-Service",
        "description": "Leichtgewichtiger Git-Server mit Web-UI, Issues, Pull Requests und CI/CD-Integration.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/gitea.png",
        "category": "Developer Tools",
        "port": 3002,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Jellyfin",
        "name": "Jellyfin",
        "tagline": "Media-Server — Filme, Serien, Musik",
        "description": "Freie Open-Source-Alternative zu Plex/Emby. Streamt Ihre lokale Mediathek auf alle Geräte.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png",
        "category": "Media",
        "port": 8097,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "HomeAssistant",
        "name": "Home Assistant",
        "tagline": "Smart Home Automation Platform",
        "description": "Verbindet und automatisiert alle Smart-Home-Geräte. Lokal, privat, über 3000 Integrationen.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png",
        "category": "Smart Home",
        "port": 8123,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Paperless-ngx",
        "name": "Paperless-ngx",
        "tagline": "Dokumenten-Management — scannen, indexieren, archivieren",
        "description": "Verwandelt physische Dokumente in ein durchsuchbares Online-Archiv. OCR, automatische Tagging, E-Mail-Import.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png",
        "category": "Documents",
        "port": 8000,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "Synapse",
        "name": "Synapse (Matrix)",
        "tagline": "Dezentraler Messaging-Server — Matrix-Protokoll",
        "description": "Eigener Matrix-Homeserver für sichere, föderierte Kommunikation. Kompatibel mit Element, FluffyChat und allen Matrix-Clients.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/element.png",
        "category": "Communication",
        "port": 8008,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Element",
        "name": "Element Web",
        "tagline": "Matrix-Client — sicherer Messenger im Browser",
        "description": "Offizieller Web-Client für das Matrix-Netzwerk. Ende-zu-Ende verschlüsselt, Räume, Gruppen, VoIP. Verbindet sich mit dem eigenen Synapse-Server.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/element.png",
        "category": "Communication",
        "port": 8088,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "OpenWebUI",
        "name": "Open WebUI",
        "tagline": "Self-hosted ChatGPT-Interface für lokale LLMs",
        "description": "Web-UI für Ollama und OpenAI-kompatible APIs. Chat, RAG, Modellverwaltung, Multi-User. Eigene KI ohne Cloud.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/open-webui.png",
        "category": "AI",
        "port": 3050,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "Ollama",
        "name": "Ollama",
        "tagline": "Lokale LLMs ausführen — Llama, Mistral, Gemma & mehr",
        "description": "Führt große Sprachmodelle lokal aus. Einfache CLI + API, Modell-Download mit einem Befehl. Ideal zusammen mit Open WebUI.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/ollama.png",
        "category": "AI",
        "port": 11434,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
    {
        "app_id": "n8n",
        "name": "n8n",
        "tagline": "Workflow-Automatisierung — Self-hosted Zapier-Alternative",
        "description": "Visueller Workflow-Builder mit 400+ Integrationen. Automatisiert Prozesse zwischen Apps, APIs und Datenbanken. Fair-Code Lizenz.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/n8n.png",
        "category": "Automation",
        "port": 5678,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Supabase",
        "name": "Supabase",
        "tagline": "Self-hosted Firebase-Alternative — Postgres, Auth, Storage, Realtime",
        "description": "Open-Source Backend-as-a-Service. PostgreSQL-Datenbank, Authentifizierung, File Storage, Realtime-Subscriptions und Edge Functions.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/supabase.png",
        "category": "Developer Tools",
        "port": 8000,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Authentik",
        "name": "Authentik",
        "tagline": "Identity Provider — SSO, OIDC, SAML, LDAP",
        "description": "Flexibler Identity Provider mit Single Sign-On, Multi-Faktor-Authentifizierung, User-Management und Application Proxy.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/authentik.png",
        "category": "Security",
        "port": 9443,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Traefik",
        "name": "Traefik",
        "tagline": "Cloud-nativer Reverse Proxy & Load Balancer",
        "description": "Automatische SSL-Zertifikate, Service Discovery, Middleware. Ideal als Eingangstor für alle Self-hosted Dienste.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/traefik.png",
        "category": "Networking",
        "port": 8080,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Coolify",
        "name": "Coolify",
        "tagline": "Self-hosted Heroku/Vercel-Alternative — PaaS",
        "description": "Deploy Apps, Datenbanken und Services mit Git-Push. Automatische SSL, Backups, Monitoring. Open-Source Platform-as-a-Service.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/coolify.png",
        "category": "Developer Tools",
        "port": 8000,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Portainer",
        "name": "Portainer",
        "tagline": "Docker-Management UI — Container, Stacks, Volumes",
        "description": "Web-basierte Verwaltung für Docker-Container, Images, Netzwerke und Volumes. Einfaches Deployment über Templates und Stacks.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png",
        "category": "Developer Tools",
        "port": 9000,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "Headscale",
        "name": "Headscale",
        "tagline": "Self-hosted Tailscale Control Server — Mesh VPN",
        "description": "Open-Source Implementierung des Tailscale Coordination Servers. Eigenes Mesh-VPN ohne Cloud-Abhängigkeit, WireGuard-basiert.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/headscale.png",
        "category": "Networking",
        "port": 8080,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
        "admin_only": True,
    },
    {
        "app_id": "RustDesk",
        "name": "RustDesk",
        "tagline": "Self-hosted Remote-Desktop — Open-Source TeamViewer-Alternative",
        "description": "Volle Kontrolle über Ihre Remote-Desktop-Infrastruktur. Eigener Relay-Server, Ende-zu-Ende verschlüsselt, plattformübergreifend.",
        "icon": "https://cdn.jsdelivr.net/gh/selfhst/icons/png/rustdesk.png",
        "category": "Remote Access",
        "port": 21118,
        "install_type": "dynamic",
        "lxc_id": None,
        "ip": None,
    },
]


def get_by_id(app_id: str) -> dict | None:
    """App-Definition anhand app_id suchen."""
    return next((a for a in PRECONFIGURED_APPS if a["app_id"] == app_id), None)


def get_fixed_params(app_id: str) -> tuple[int | None, str | None]:
    """Gibt (fixed_lxc_id, fixed_ip) zurück — None wenn dynamic."""
    app = get_by_id(app_id)
    if app and app["install_type"] == "fixed":
        return app["lxc_id"], app["ip"]
    return None, None
