# schuetzenverein Website
image:
  repository: war10ck-2025/schuetzenverein-niederklein-website
containerPort: 80
service:
  port: 80
ingress:
  host: schuetzenverein.k8s.jarvis.local
labels:
  component: website
